import React, { useEffect, useState } from 'react';
import { Layout } from '../components/layout/Layout';
import { Card } from '../components/common/Card';
import { useApi } from '../hooks/useApi';
import { fetchAlerts, fetchHealth } from '../services/api';
import { Server, ShieldCheck, Radio, Globe, Save } from 'lucide-react';

const SOURCES = ['SIEM','EDR','Network Sensor','Threat Intel'];

export const Settings: React.FC = () => {
  const { data: health, refetch: refreshHealth } = useApi(fetchHealth);
  const { data: alerts } = useApi(fetchAlerts);
  const [confidenceThreshold,setConfidenceThreshold]=useState(()=>Number(localStorage.getItem('threatlens.confidence')||'65'));
  const [autoIsolate,setAutoIsolate]=useState(()=>localStorage.getItem('threatlens.autoIsolate')!=='false');
  const [emailAlerts,setEmailAlerts]=useState(()=>localStorage.getItem('threatlens.emailAlerts')!=='false');
  const [analystName,setAnalystName]=useState(()=>localStorage.getItem('threatlens.analystName')||'SOC Analyst');
  const [saved,setSaved]=useState(false);
  useEffect(()=>{localStorage.setItem('threatlens.confidence',String(confidenceThreshold));localStorage.setItem('threatlens.autoIsolate',String(autoIsolate));localStorage.setItem('threatlens.emailAlerts',String(emailAlerts));localStorage.setItem('threatlens.analystName',analystName)},[confidenceThreshold,autoIsolate,emailAlerts,analystName]);
  const sourceMeta=[{name:'SIEM',type:'SIEM telemetry',icon:Server},{name:'EDR',type:'Endpoint telemetry',icon:ShieldCheck},{name:'Network Sensor',type:'Network telemetry',icon:Radio},{name:'Threat Intel',type:'Threat intelligence',icon:Globe}];
  const activeSources= new Set((alerts??[]).map(a=>a.source));
  const save=()=>{setSaved(true);refreshHealth();setTimeout(()=>setSaved(false),1600)};
  return <Layout>
    <div className="pb-2 border-b border-slate-800/80"><h1 className="text-2xl font-bold text-slate-100">System Settings</h1><p className="text-xs text-slate-400 mt-1">Live environment status and locally persisted analyst preferences</p></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="lg:col-span-2 space-y-6">
      <Card title="Connected Intelligence Feeds" subtitle="Availability is derived from the alerts currently stored by the backend"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{sourceMeta.map(ds=>{const Icon=ds.icon;const count=(alerts??[]).filter(a=>a.source===ds.name).length;return <div key={ds.name} className="p-4 rounded-xl bg-slate-950 border border-slate-800"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-lg bg-slate-900 border border-slate-800 flex items-center justify-center text-cyan-400"><Icon className="w-5 h-5"/></div><div><h4 className="font-semibold text-slate-100 text-xs">{ds.name}</h4><span className="text-[11px] text-slate-400">{ds.type}</span></div></div><span className={`text-[10px] font-mono ${activeSources.has(ds.name)?'text-emerald-400':'text-slate-500'}`}>{activeSources.has(ds.name)?'ACTIVE':'NO DATA'}</span></div><div className="mt-4 pt-3 border-t border-slate-900 text-[11px] font-mono text-slate-400">{count} stored alert{count===1?'':'s'}</div></div>})}</div></Card>
      <Card title="Correlation Preferences" subtitle="These preferences are persisted in this browser for the current demo operator"><div className="space-y-6 text-xs"><div><div className="flex justify-between mb-2"><label className="font-semibold text-slate-200">Minimum correlation confidence</label><span className="font-mono font-bold text-cyan-400">{confidenceThreshold}%</span></div><input type="range" min="50" max="99" value={confidenceThreshold} onChange={e=>setConfidenceThreshold(Number(e.target.value))} className="w-full accent-cyan-500"/></div><div className="pt-4 border-t border-slate-800 space-y-4"><label className="flex items-center justify-between"><span><b className="text-slate-200 block">Automatic endpoint isolation</b><small className="text-slate-400">Preference only; no destructive action is executed by this demo.</small></span><input type="checkbox" checked={autoIsolate} onChange={e=>setAutoIsolate(e.target.checked)} className="w-5 h-5 accent-cyan-500"/></label><label className="flex items-center justify-between"><span><b className="text-slate-200 block">Analyst notifications</b><small className="text-slate-400">Preference for priority incident notifications.</small></span><input type="checkbox" checked={emailAlerts} onChange={e=>setEmailAlerts(e.target.checked)} className="w-5 h-5 accent-cyan-500"/></label></div><button onClick={save} className="px-4 py-2 rounded-lg bg-cyan-600 text-slate-950 font-bold flex items-center gap-2"><Save className="w-4 h-4"/>{saved?'Saved':'Save Preferences'}</button></div></Card>
    </div><div className="space-y-6"><Card title="Analyst Profile" subtitle="Browser-local operator profile"><div className="space-y-4 text-xs"><label className="block"><span className="text-slate-400">Display name</span><input value={analystName} onChange={e=>setAnalystName(e.target.value)} className="mt-2 w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-slate-200"/></label><div className="p-3 rounded-lg bg-slate-950 border border-slate-800"><span className="text-[10px] text-slate-400 uppercase">Role</span><p className="font-semibold text-cyan-400 mt-1">Incident Analyst</p></div></div></Card><Card title="Live Backend Status" subtitle="Read from FastAPI health endpoint"><div className="space-y-3 text-xs"><p>Status: <b className="text-emerald-400">{health?.status ?? '—'}</b></p><p>Version: <b className="text-cyan-400">{health?.version ?? '—'}</b></p><p>Environment: <b>{health?.environment ?? '—'}</b></p><p>Alerts: <b>{health?.alertCount ?? '—'}</b></p><p>Incidents: <b>{health?.incidentCount ?? '—'}</b></p></div></Card><Card title="Feed Coverage" subtitle="Sources represented in current telemetry"><div className="text-2xl font-bold text-cyan-400">{activeSources.size} / {SOURCES.length}</div><p className="text-xs text-slate-400 mt-1">Active source types with at least one stored alert</p></Card></div></div>
  </Layout>
};
