import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Layout } from '../components/layout/Layout';
import { Card } from '../components/common/Card';
import { searchThreatIndicator, fetchIndicators, type IndicatorResult } from '../services/api';
import { Search, Globe, ArrowDown, ExternalLink, RefreshCw } from 'lucide-react';

export const ThreatIntelligence: React.FC = () => {
  const navigate=useNavigate(); const [indicators,setIndicators]=useState<IndicatorResult[]>([]); const [selected,setSelected]=useState<IndicatorResult|null>(null); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [searching,setSearching]=useState(false); const [error,setError]=useState('');
  const load=async()=>{setLoading(true);try{const r=await fetchIndicators();setIndicators(r.indicators);if(!selected&&r.indicators[0])setSelected(r.indicators[0]);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load live threat intelligence.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const search=async(e:React.FormEvent)=>{e.preventDefault();if(!query.trim())return;setSearching(true);try{setSelected(await searchThreatIndicator(query.trim()));setError('')}catch(e){setError(e instanceof Error?e.message:'Indicator search failed')}finally{setSearching(false)}};
  return <Layout>
    <div className="pb-2 border-b border-slate-800/80"><h1 className="text-2xl font-bold text-slate-100">Threat Intelligence</h1><p className="text-xs text-slate-400 mt-1">Live indicator intelligence derived from ingested telemetry and correlated incidents</p></div>
    {error&&<div className="p-3 rounded-xl bg-red-950/40 border border-red-900 text-red-300 text-xs">{error}</div>}
    <Card glow="cyan"><form onSubmit={search} className="space-y-4"><label className="block text-xs font-semibold text-slate-300 uppercase tracking-wider">Search Indicator of Compromise</label><div className="flex gap-3"><div className="relative flex-1"><Search className="w-4 h-4 text-slate-500 absolute left-3.5 top-1/2 -translate-y-1/2"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search observed IP, domain, hash or URL…" className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-10 pr-4 py-3 text-sm text-slate-200 font-mono"/></div><button disabled={searching} className="px-6 py-3 rounded-xl bg-cyan-600 text-slate-950 font-extrabold text-xs flex items-center gap-2"><Globe className={searching?'animate-spin':''}/>{searching?'Analyzing…':'Analyze Indicator'}</button></div></form></Card>
    <Card title="Observed Indicators" subtitle={`${indicators.length} indicators derived from current backend telemetry`}><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">{loading?<div className="text-sm text-slate-500">Loading…</div>:indicators.map(ind=><button key={ind.value} onClick={()=>setSelected(ind)} className={`text-left p-4 rounded-xl border ${selected?.value===ind.value?'border-cyan-700 bg-cyan-950/30':'border-slate-800 bg-slate-950 hover:border-slate-700'}`}><div className="font-mono text-cyan-300 text-sm break-all">{ind.value}</div><div className="mt-2 flex justify-between text-[11px]"><span className="text-slate-400">{ind.type}</span><span className={ind.reputation==='MALICIOUS'?'text-red-400':ind.reputation==='SUSPICIOUS'?'text-amber-400':'text-emerald-400'}>{ind.reputation}</span></div></button>)}</div></Card>
    {selected&&<div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card title="Indicator Intelligence" subtitle="Backend-derived reputation and observation history"><div className="space-y-4 text-xs"><div className="p-4 rounded-xl bg-slate-950 border border-slate-800"><span className="text-[10px] text-slate-400 uppercase">Indicator</span><p className="font-mono font-extrabold text-cyan-400 text-base mt-1 break-all">{selected.value}</p></div><div className="grid grid-cols-2 gap-3"><div className="p-3 rounded bg-slate-950 border border-slate-800"><span className="text-slate-500">Type</span><b className="block mt-1">{selected.type}</b></div><div className="p-3 rounded bg-slate-950 border border-slate-800"><span className="text-slate-500">Reputation</span><b className="block mt-1">{selected.reputation}</b></div><div className="p-3 rounded bg-slate-950 border border-slate-800"><span className="text-slate-500">Confidence</span><b className="block mt-1 text-cyan-400">{selected.confidence}%</b></div><div className="p-3 rounded bg-slate-950 border border-slate-800"><span className="text-slate-500">Observations</span><b className="block mt-1">{selected.associatedIncidents.length} incidents</b></div></div><div><span className="text-slate-500">First seen</span><p className="font-mono text-slate-300">{selected.firstSeen||'—'}</p><span className="text-slate-500">Last seen</span><p className="font-mono text-slate-300">{selected.lastSeen||'—'}</p></div></div></Card>
    <Card title="Relationship Correlation" subtitle="Live links from indicator to incidents and ATT&CK"><div className="p-5 bg-slate-950 rounded-xl border border-slate-800 space-y-5"><div className="text-center"><div className="font-mono text-cyan-300 break-all">{selected.value}</div><div className="text-[10px] text-slate-500 mt-1">{selected.type} • {selected.confidence}% confidence</div></div><ArrowDown className="mx-auto text-slate-600"/><div><div className="text-[10px] uppercase text-slate-500 mb-2">Associated incidents</div>{selected.associatedIncidents.length?<div className="flex flex-wrap gap-2">{selected.associatedIncidents.map(id=><button key={id} onClick={()=>navigate(`/incidents/${id}`)} className="px-2 py-1 rounded bg-purple-950 text-purple-300 border border-purple-800 font-mono text-xs flex items-center gap-1">{id}<ExternalLink className="w-3 h-3"/></button>)}</div>:<span className="text-xs text-slate-500">No correlated incidents</span>}</div><div><div className="text-[10px] uppercase text-slate-500 mb-2">MITRE techniques</div><div className="flex flex-wrap gap-2">{selected.relatedMitre.length?selected.relatedMitre.map(t=><span key={t} className="px-2 py-1 rounded bg-cyan-950 border border-cyan-800 text-cyan-300 text-xs font-mono">{t}</span>):<span className="text-xs text-slate-500">No mapped techniques</span>}</div></div></div></Card>
    <Card title="Live Feed State" subtitle="Backend source status"><div className="space-y-3 text-xs"><div className="p-3 rounded bg-slate-950 border border-slate-800">{indicators.length} observed indicators currently available.</div><button onClick={()=>void load()} className="px-3 py-2 rounded-lg bg-slate-900 border border-slate-800 text-slate-200 flex items-center gap-2"><RefreshCw className="w-4 h-4"/>Refresh intelligence</button></div></Card></div>}
  </Layout>
};
